spring.application.name=demo

# Configuración de Base de Datos (Neon PostgreSQL)
# Reemplaza [HOST_NEON], [USUARIO], y [CONTRASEÑA] con tus datos de Neon.
# Por ejemplo, si Neon te da la URL: postgresql://fiape-backend_owner:neondbpass@ep-cool-water-a5xyz.us-east-2.aws.neon.tech/fiape-backend?sslmode=require
# Tu HOST_NEON será: ep-cool-water-a5xyz.us-east-2.aws.neon.tech
spring.datasource.url=jdbc:postgresql://[HOST_NEON]/fiape-backend?sslmode=require
spring.datasource.username=[USUARIO]
spring.datasource.password=[CONTRASEÑA]
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de Swagger
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs